

name: CI
on:
  push:
    branches:
      - main
env:
  RUN_ID: ${{ github.run_id }}

jobs:
  # pytest:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Run tests
  #     working-directory: /pytest
  #     run: |
  #       pip install pytest
  #       python -m pytest testing.py      
  whisper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: Run Whisper API
        run: python airflow/dags/healthcheck.py

      - name: Run Chat API
        run: python openapi/whisperapi.py
      

      - name: Trigger Airflow DAG
        run: |
          curl -X POST \
            -H "Cache-Control: no-cache" \
            -H "Content-Type: application/json" \
            -u "{{ secrets.AIRFLOW_USERNAME }}:{{ secrets.AIRFLOW_PASSWORD}}" \
            -d '{ "dag_id": "my_dag", "run_id": ${{ env.RUN_ID }} }' \
            "http://35.237.121.118:8080/api/v1/dags/my_dag/dagRuns"

  
 

